CREATE DATABASE RECORD_COMPANY;
USE RECORD_COMPANY;

CREATE TABLE BAND (
ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(250) NOT NULL,
PRIMARY KEY (ID));

CREATE TABLE ALBUM (
ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(250) NOT NULL,
YEAR INT,
BAND_ID INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (BAND_ID) REFERENCES BAND(ID));

INSERT INTO BAND(NAME) VALUES ('Iron Maiden');
INSERT INTO BAND(NAME) VALUES('DEUCE');
INSERT INTO BAND(NAME) VALUES ('AVENGED SEVENFOLD');
INSERT INTO BAND(NAME) VALUES ('ANKOR');

SELECT * FROM BAND;
SELECT * FROM BAND LIMIT 1;
SELECT * FROM BAND LIMIT 2;
SELECT NAME FROM BAND;
SELECT NAME FROM BAND LIMIT 1;

SELECT ID AS 'ID_NUMBER', NAME AS 'TITLE' FROM BAND;

SELECT * FROM BAND ORDER BY NAME;
SELECT * FROM BAND ORDER BY NAME DESC;

INSERT INTO ALBUM(NAME, YEAR, BAND_ID) VALUES ('The Number of the Beasts', 1985, 1);
INSERT INTO ALBUM(NAME, YEAR, BAND_ID) VALUES ('Power Slave', 1984, 1);
INSERT INTO ALBUM(NAME, YEAR, BAND_ID) VALUES ('Nightmare', 2018, 2);
INSERT INTO ALBUM(NAME, YEAR, BAND_ID) VALUES ('Love', 2010, 3);
INSERT INTO ALBUM(NAME, YEAR, BAND_ID) VALUES ('Test Album', NULL, 3);

SELECT * FROM ALBUM;
SELECT NAME FROM ALBUM;
SELECT YEAR FROM ALBUM;
SELECT NAME, YEAR FROM ALBUM WHERE YEAR IS NOT NULL ORDER BY YEAR DESC;
SELECT NAME, YEAR FROM ALBUM WHERE YEAR IS NOT NULL ORDER BY YEAR DESC LIMIT 1;

SELECT * FROM ALBUM WHERE YEAR IS NOT NULL ORDER BY YEAR DESC;
SELECT NAME, YEAR FROM ALBUM WHERE YEAR IS NOT NULL ORDER BY YEAR;

SELECT DISTINCT NAME FROM ALBUM;

UPDATE ALBUM SET YEAR=2018 WHERE ID=1;
SELECT * FROM ALBUM;

SELECT * FROM ALBUM WHERE YEAR<1985;
SELECT * FROM ALBUM WHERE NAME LIKE '%er%';
SELECT * FROM ALBUM WHERE NAME LIKE '%er%' OR BAND_ID=2;
SELECT * FROM ALBUM WHERE YEAR=1984 AND BAND_ID=1;
SELECT * FROM ALBUM WHERE YEAR BETWEEN 1980 AND 2010;
SELECT * FROM ALBUM WHERE YEAR IS NULL;

DELETE FROM ALBUM WHERE ID=5;
SELECT * FROM ALBUM;

SELECT NAME, MIN(YEAR) FROM ALBUM;
SELECT SUM(YEAR) FROM ALBUM;
SELECT AVG(YEAR) FROM ALBUM;

SELECT BAND_ID, COUNT(BAND_ID) FROM ALBUM GROUP BY BAND_ID;
SELECT BAND_ID AS 'BAND', COUNT(BAND_ID) AS 'NUMBER OF ALBUMS IN THE BAND' FROM ALBUM GROUP BY BAND_ID;

SELECT * FROM ALBUM LEFT JOIN BAND ON ALBUM.BAND_ID=BAND.ID;
SELECT ALBUM.NAME AS 'ALBUM', YEAR, BAND.NAME AS 'BAND' FROM ALBUM LEFT JOIN BAND ON ALBUM.BAND_ID=BAND.ID;

SELECT BAND.NAME AS 'BAND NAME', COUNT(BAND_ID) AS 'NUMBER OF ALBUMS' 
FROM ALBUM LEFT JOIN BAND ON ALBUM.BAND_ID=BAND.ID 
GROUP BY BAND.ID
HAVING COUNT(BAND_ID)=1; 

-- DROP DATABASE record_company; 